language: node_js
cache:
  directories:
    - node_modules
node_js: 
  - 12
  - 11
  - 8
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage
